### ISSUE TITLE
Potential dependency conflicts between djabberd and django

### ISSUE THREAD

**Issue by NeolithEra** [alej0varas/djabberd#3]
Hi, as shown in the following full dependency graph of djabberd, djabberd requires **_django <2,>=1.8_** ， while the installed version of **_django (1.11.29)_** ，**_djangorestframework 3.11.0_** requires **_django >=1.11_**.
According to Pip's _“first found wins”_ installation strategy, **_django 1.11.29_** is the actually installed version.
Although the first found package version **_django 1.11.29_** just satisfies the later dependency constraint **_（django >=1.11)_**, it will easily cause a build failure once the updated **_djangorestframework_** introduces a higher version of **_django_**.
According to the release history of **_djangorestframework_**, it habitually upgrates **_django_** in its recent releases. For instance, **_djangorestframework_** next version upgrated **_django’s_** constraint from _**>=1.11**_ to _**>=2.2**_, **_djangorestframework 3.10_** upgrated **_django’s_** constraint from **_*_** to **_>=1.11_**. 

### Dependency tree
```
djabberd - 0.9.6
| +- django(install version:1.11.29 version range:<2,>=1.8)
| | +- pytz(install version:2019.3 version range:*)
| +- djangorestframework(install version:3.11.0 version range:<4,>=3.2)
| | +- django(install version:1.11.29 version range:>=1.11)
| | | +- pytz(install version:2019.3 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution
1.	Lose the version range of **_django_** to be **_>=1.8_**.
2.	Remove your direct dependency **_django_**, and use the **_django_** transitively introduced by **_djangorestframework_**.
3.  Change the version range of  **_djangorestframework_** to be _**<3.11.0,>=3.2**_.
@alej0varas Which solution do you prefer, 1 ,2or 3?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by alej0varas** [comment]
Hi NeolithEra, I think option 2 is the right one. Only having **djangorestframwork** as dependency.

**Notice** that I've just pushed a commit to github. It's the commit for version 0.96(latest one on pypi).

It will be great if you submit a pull request ;)

**Comment by alej0varas** [comment]
@NeolithEra I've made the change to the requirements. Could you test it?

**Comment by NeolithEra** [comment]
@alej0varas  It looks good to me. Thanks for your help.
